source 'https://rubygems.org'

gem 'jekyll'
gem 'just-the-docs'
gem 'webrick'

# GitHub Pages plugins
group :jekyll_plugins do
  gem 'jekyll-remote-theme'
  gem 'jekyll-seo-tag'
  gem 'jekyll-sitemap'
  gem 'jekyll-og-image', git: 'https://github.com/crmne/jekyll-og-image'
end
